# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mtm-configmap
data:
{{- with .Values.resultsConfig }}
  appsettings.json: |-
    {{- . | nindent 4 }}
{{- else }}
  appsettings.json: >
{{ .Files.Get "files/task-manager.json" | indent 4 }}
{{- end }}
